create database Fernandez_Herrera_DB
GO
use Fernandez_Herrera_DB
GO
create table USUARIOS(
 ID BIGINT NOT NULL PRIMARY KEY,
 NOMBREUSUARIO VARCHAR NOT NULL UNIQUE,
 NOMBRE VARCHAR NOT NULL , 
 APELLIDO VARCHAR NOT NULL,
 FECHANAC VARCHAR NOT NULL,
 DNI BIGINT NOT NULL UNIQUE,
 PASS VARCHAR NOT NULL,
 TIPO VARCHAR NOT NULL
)
GO
create table MENSAJES (
ID BIGINT NOT NULL PRIMARY KEY,
IDUSUARIO BIGINT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID),
ESTADO BIT NOT NULL,
MENSAJE VARCHAR,
RESPUESTA VARCHAR,

)

GO
create table MARCAS (
ID INT NOT NULL PRIMARY	KEY identity(1,1),
DESCRIPCION VARCHAR (100)NOT NULL
)
GO
create table CATEGORIAS (
ID INT NOT NULL PRIMARY	KEY identity(1,1),
DESCRIPCION VARCHAR (100)NOT NULL
)

GO
create table COMPONENTES (
 ID BIGINT NOT NULL PRIMARY KEY,
 NOMBRE VARCHAR,
 DESCRIPCION VARCHAR,
 IMAGENURL VARCHAR,
 IDMARCA INT NOT NULL FOREIGN KEY REFERENCES MARCAS(ID),
 IDCATEGORIA INT NOT NULL FOREIGN KEY REFERENCES CATEGORIAS(ID),
)
GO
create table MOTHERBOARDS(
 IDCOMPONENTE BIGINT NOT NULL FOREIGN KEY REFERENCES COMPONENTES(ID),
 CANTUSB INT NOT NULL,
 SOCKET VARCHAR NOT NULL,
 CAPACIDADRAM VARCHAR NOT NULL,
 CANTSATA INT NOT NULL,
 PUERTOS VARCHAR
)
GO
create table PROCESADORES(
IDCOMPONENTE BIGINT NOT NULL FOREIGN KEY REFERENCES COMPONENTES(ID),
 SOCKET VARCHAR NOT NULL,
 CANTNUCLEOS INT NOT NULL,
 FRECUENCIA FLOAT NOT NULL
)
GO 
create table RAMS(
 IDCOMPONENTE BIGINT NOT NULL FOREIGN KEY REFERENCES COMPONENTES(ID),
 DDR INT NOT NULL,
 CAPACIDAD INT NOT NULL,
 VELOCIDAD INT NOT NULL,
)
GO
create table DISCORIGIDOS(
 IDCOMPONENTE BIGINT NOT NULL FOREIGN KEY REFERENCES COMPONENTES(ID),
 CAPACIDAD VARCHAR NOT NULL,
)
GO
create table FUENTES(
IDCOMPONENTE BIGINT NOT NULL FOREIGN KEY REFERENCES COMPONENTES(ID),
POTENCIA VARCHAR NOT NULL,
CERTIFICACION VARCHAR
)
GO
create table GABIENTES(
IDCOMPONENTE BIGINT NOT NULL FOREIGN KEY REFERENCES COMPONENTES(ID),
TAMANIOMOTHER VARCHAR,
CANTUSB INT
)
GO
create table PLACASDEVIDEO(
IDCOMPONENTE BIGINT NOT NULL FOREIGN KEY REFERENCES COMPONENTES(ID),
CAPACIDAD INT,
PUERTOS VARCHAR,
)
GO 
create table PANTALLAS
(
IDCOMPONENTE BIGINT NOT NULL FOREIGN KEY REFERENCES COMPONENTES(ID),
PULGADAS INT NOT NULL,
RESOLUCION VARCHAR NOT NULL
)
GO
create table ITEMS (
ID BIGINT NOT NULL PRIMARY KEY,
IDCOMPONENTE BIGINT NOT NULL FOREIGN KEY REFERENCES COMPONENTES(ID),
CANTIDAD INT NOT NULL,
SUBTOTAL MONEY CHECK(SUBTOTAL > 0),
)
GO
create table CARRITO(
ID INT NOT NULL PRIMARY KEY,
IDUSUARIO BIGINT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID), 
IDITEM BIGINT NOT NULL FOREIGN KEY REFERENCES ITEMS(ID),
TOTAL MONEY NOT NULL
)

insert  into categorias values('Accesorios')
insert  into categorias values('Auriculares') 
insert  into categorias values('Microfonos')
insert  into categorias values('Cables')
insert  into categorias values('Cargadores')
insert  into categorias values('Cartucho Alternativo hp')
insert  into categorias values('Cartuchos Alternativos Epson')
insert  into categorias values('Cartuchos Originales Epson')
insert  into categorias values('Cartuchos Originales hp')
insert  into categorias values('Celulares y Tablets')
